sudo: required
services:
  - docker
before_install:
  - docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$TRAV -f [dockerfile] .
script:
  - docker run -e CI=true $DOCKER_USERNAME/$DOCKER_REPOSITORY:$TRAV npm run test
