version: '1'

volumes:
  clientapp:
  
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/
      - clientapp:/usr/app/node_modules
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - clientapp:/usr/app/node_modules
      - .:/usr/app/
    command: ["npm", "run", "test"]
